# Generated by Django 6.0.5 on 2026-05-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('clothing', 'clothing'), ('shoes', 'shoes'), ('watches', 'watches'), ('jewelry', 'jewelry'), ('headwear', 'headwear')], default='clothing')),
                ('description', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
