# Generated by Django 6.0.5 on 2026-05-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cart_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
